- name: Setup mitmproxy container with custom port and redirection
  hosts: localhost
  vars:
    default_ports: [8180]
    ports_list: "{{ ports.split(',') | map('int') | list }}"
  tasks:
    - name: Build mitmproxy Docker image
      docker_image:
        name: mitmproxy_image
        source: build
        build:
          path: ./
          pull: yes
      tags:
        - build

    - name: Run mitmproxy container
      docker_container:
        name: mitmproxy_container
        image: mitmproxy_image
        state: started
        ports:
          - "{{ item }}:{{ item }}"
          - "{{ item + 1 }}:{{ item + 1 }}"
        volumes:
          - "./redirect.py:/home/mitmproxy/redirect.py"
        command: "mitmweb --listen-host 0.0.0.0 --listen-port {{ item }} -s /home/mitmproxy/redirect.py --web-host 0.0.0.0 --web-port {{ item + 1 }}"
      with_items: "{{ ports_list }}"
      tags:
        - run

    - name: Execute port forwarding script
      ansible.builtin.script: run-port-forward.sh "{{ ports }}"
      tags:
        - port_forward

    - name: Cleanup previous port forwarding and firewall rules
      ansible.builtin.script: run-cleanup.sh "{{ ports }}"
      tags:
        - cleanup
